<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2015, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201506;
use Google\Api\Ads\AdWords\Lib\AdWordsSoapClient;

/**
   * DataService
   * @package Google_Api_Ads_AdWords_v201506
   * @subpackage v201506
   */
class DataService extends AdWordsSoapClient
{
    const SERVICE_NAME = 'DataService';
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/cm/v201506';
    const ENDPOINT = 'https://adwords.google.com/api/adwords/cm/v201506/DataService';
    /**
     * The endpoint of the service
     * @var string
     */
    public static $endpoint = 'https://adwords.google.com/api/adwords/cm/v201506/DataService';
    /**
     * Default class map for wsdl=>php
     * @access private
     * @var array
     */
    public static $classmap = array(
        'AdGroupBidLandscape'                => AdGroupBidLandscape::class,
        'AdxError'                           => AdxError::class,
        'AuthenticationError'                => AuthenticationError::class,
        'AuthorizationError'                 => AuthorizationError::class,
        'ClientTermsError'                   => ClientTermsError::class,
        'DateError'                          => DateError::class,
        'DateRange'                          => DateRange::class,
        'DistinctError'                      => DistinctError::class,
        'DoubleValue'                        => DoubleValue::class,
        'IdError'                            => IdError::class,
        'InternalApiError'                   => InternalApiError::class,
        'LevelOfDetail'                      => LevelOfDetail::class,
        'LongValue'                          => LongValue::class,
        'Money'                              => Money::class,
        'NotEmptyError'                      => NotEmptyError::class,
        'NullError'                          => NullError::class,
        'NumberValue'                        => NumberValue::class,
        'OperationAccessDenied'              => OperationAccessDenied::class,
        'OrderBy'                            => OrderBy::class,
        'Paging'                             => Paging::class,
        'Predicate'                          => Predicate::class,
        'QueryError'                         => QueryError::class,
        'QuotaCheckError'                    => QuotaCheckError::class,
        'RangeError'                         => RangeError::class,
        'RateExceededError'                  => RateExceededError::class,
        'ReadOnlyError'                      => ReadOnlyError::class,
        'RejectedError'                      => RejectedError::class,
        'RequestError'                       => RequestError::class,
        'RequiredError'                      => RequiredError::class,
        'SelectorError'                      => SelectorError::class,
        'SizeLimitError'                     => SizeLimitError::class,
        'SoapHeader'                         => SoapRequestHeader::class,
        'SoapResponseHeader'                 => SoapResponseHeader::class,
        'StringLengthError'                  => StringLengthError::class,
        'DataError'                          => DataError::class,
        'ComparableValue'                    => ComparableValue::class,
        'CriterionBidLandscape'              => CriterionBidLandscape::class,
        'DatabaseError'                      => DatabaseError::class,
        'DomainCategory'                     => DomainCategory::class,
        'ApiError'                           => ApiError::class,
        'ApiException'                       => ApiException::class,
        'ApplicationException'               => ApplicationException::class,
        'BidLandscape.LandscapePoint'        => BidLandscapeLandscapePoint::class,
        'Selector'                           => Selector::class,
        'BidLandscape'                       => BidLandscape::class,
        'DimensionProperties'                => DimensionProperties::class,
        'DataEntry'                          => DataEntry::class,
        'AdGroupBidLandscapePage'            => AdGroupBidLandscapePage::class,
        'CriterionBidLandscapePage'          => CriterionBidLandscapePage::class,
        'DomainCategoryPage'                 => DomainCategoryPage::class,
        'NoStatsPage'                        => NoStatsPage::class,
        'Page'                               => Page::class,
        'AdGroupBidLandscape.Type'           => AdGroupBidLandscapeType::class,
        'AdxError.Reason'                    => AdxErrorReason::class,
        'AuthenticationError.Reason'         => AuthenticationErrorReason::class,
        'AuthorizationError.Reason'          => AuthorizationErrorReason::class,
        'ClientTermsError.Reason'            => ClientTermsErrorReason::class,
        'DatabaseError.Reason'               => DatabaseErrorReason::class,
        'DateError.Reason'                   => DateErrorReason::class,
        'DistinctError.Reason'               => DistinctErrorReason::class,
        'IdError.Reason'                     => IdErrorReason::class,
        'InternalApiError.Reason'            => InternalApiErrorReason::class,
        'NotEmptyError.Reason'               => NotEmptyErrorReason::class,
        'NullError.Reason'                   => NullErrorReason::class,
        'OperationAccessDenied.Reason'       => OperationAccessDeniedReason::class,
        'Predicate.Operator'                 => PredicateOperator::class,
        'QueryError.Reason'                  => QueryErrorReason::class,
        'QuotaCheckError.Reason'             => QuotaCheckErrorReason::class,
        'RangeError.Reason'                  => RangeErrorReason::class,
        'RateExceededError.Reason'           => RateExceededErrorReason::class,
        'ReadOnlyError.Reason'               => ReadOnlyErrorReason::class,
        'RejectedError.Reason'               => RejectedErrorReason::class,
        'RequestError.Reason'                => RequestErrorReason::class,
        'RequiredError.Reason'               => RequiredErrorReason::class,
        'SelectorError.Reason'               => SelectorErrorReason::class,
        'SizeLimitError.Reason'              => SizeLimitErrorReason::class,
        'SortOrder'                          => SortOrder::class,
        'StringLengthError.Reason'           => StringLengthErrorReason::class,
        'DataError.Reason'                   => DataErrorReason::class,
        'getAdGroupBidLandscape'             => GetAdGroupBidLandscape::class,
        'getAdGroupBidLandscapeResponse'     => GetAdGroupBidLandscapeResponse::class,
        'getCriterionBidLandscape'           => GetCriterionBidLandscape::class,
        'getCriterionBidLandscapeResponse'   => GetCriterionBidLandscapeResponse::class,
        'getDomainCategory'                  => GetDomainCategory::class,
        'getDomainCategoryResponse'          => GetDomainCategoryResponse::class,
        'queryAdGroupBidLandscape'           => QueryAdGroupBidLandscape::class,
        'queryAdGroupBidLandscapeResponse'   => QueryAdGroupBidLandscapeResponse::class,
        'queryCriterionBidLandscape'         => QueryCriterionBidLandscape::class,
        'queryCriterionBidLandscapeResponse' => QueryCriterionBidLandscapeResponse::class,
        'queryDomainCategory'                => QueryDomainCategory::class,
        'queryDomainCategoryResponse'        => QueryDomainCategoryResponse::class,
    );

    /**
     * Constructor using wsdl location and options array
     * @param string $wsdl WSDL location for this service
     * @param array $options Options for the SoapClient
     */
    public function __construct($wsdl, $options, $user)
    {
        $options['classmap'] = self::$classmap;
        parent::__construct($wsdl, $options, $user, self::SERVICE_NAME, self::WSDL_NAMESPACE);
    }
    /**
     * <span class="constraint Required">This field is required and should not be {@code null}.</span>
     * 
     * 
     * 
     * Returns a list of {@link AdGroupBidLandscape}s for the ad groups specified in the selector.
     * In the result, the returned {@link LandscapePoint}s are grouped into
     * {@link AdGroupBidLandscape}s by their ad groups, and numberResults of paging limits the total
     * number of {@link LandscapePoint}s instead of number of {@link AdGroupBidLandscape}s.
     * 
     * @param serviceSelector Selects the entities to return bid landscapes for.
     * @return A list of bid landscapes.
     * @throws ApiException when there is at least one error with the request.
     */
    public function getAdGroupBidLandscape($serviceSelector)
    {
        $args = new GetAdGroupBidLandscape($serviceSelector);
        $result = $this->__soapCall('getAdGroupBidLandscape', array($args));
        return $result->rval;
    }
    /**
     * <span class="constraint Required">This field is required and should not be {@code null}.</span>
     * 
     * 
     * 
     * Returns a list of {@link CriterionBidLandscape}s for the criteria specified in the selector.
     * In the result, the returned {@link LandscapePoint}s are grouped into
     * {@link CriterionBidLandscape}s by their criteria, and numberResults of paging limits the total
     * number of {@link LandscapePoint}s instead of number of {@link CriterionBidLandscape}s.
     * 
     * @param serviceSelector Selects the entities to return bid landscapes for.
     * @return A list of bid landscapes.
     * @throws ApiException when there is at least one error with the request.
     */
    public function getCriterionBidLandscape($serviceSelector)
    {
        $args = new GetCriterionBidLandscape($serviceSelector);
        $result = $this->__soapCall('getCriterionBidLandscape', array($args));
        return $result->rval;
    }
    /**
     * <span class="constraint Required">This field is required and should not be {@code null}.</span>
     * 
     * 
     * 
     * Returns a list of domain categories that can be used to create {@link WebPage} criterion.
     * 
     * @param serviceSelector Selects the entities to return domain categories for.
     * @return A list of domain categories.
     * @throws ApiException when there is at least one error with the request.
     */
    public function getDomainCategory($serviceSelector)
    {
        $args = new GetDomainCategory($serviceSelector);
        $result = $this->__soapCall('getDomainCategory', array($args));
        return $result->rval;
    }
    /**
     * <span class="constraint Required">This field is required and should not be {@code null}.</span>
     * 
     * 
     * 
     * Returns a list of {@link AdGroupBidLandscape}s for the ad groups that match the query. In the
     * result, the returned {@link LandscapePoint}s are grouped into {@link AdGroupBidLandscape}s
     * by their ad groups, and numberResults of paging limits the total number of
     * {@link LandscapePoint}s instead of number of {@link AdGroupBidLandscape}s.
     * 
     * @param query The SQL-like AWQL query string.
     * @return A list of bid landscapes.
     * @throws ApiException if problems occur while parsing the query or fetching bid landscapes.
     */
    public function queryAdGroupBidLandscape($query)
    {
        $args = new QueryAdGroupBidLandscape($query);
        $result = $this->__soapCall('queryAdGroupBidLandscape', array($args));
        return $result->rval;
    }
    /**
     * <span class="constraint Required">This field is required and should not be {@code null}.</span>
     * 
     * 
     * 
     * Returns a list of {@link CriterionBidLandscape}s for the criteria that match the query. In the
     * result, the returned {@link LandscapePoint}s are grouped into {@link CriterionBidLandscape}s
     * by their criteria, and numberResults of paging limits the total number of
     * {@link LandscapePoint}s instead of number of {@link CriterionBidLandscape}s.
     * 
     * @param query The SQL-like AWQL query string.
     * @return A list of bid landscapes.
     * @throws ApiException if problems occur while parsing the query or fetching bid landscapes.
     */
    public function queryCriterionBidLandscape($query)
    {
        $args = new QueryCriterionBidLandscape($query);
        $result = $this->__soapCall('queryCriterionBidLandscape', array($args));
        return $result->rval;
    }
    /**
     * <span class="constraint Required">This field is required and should not be {@code null}.</span>
     * 
     * 
     * 
     * Returns a list of domain categories that can be used to create {@link WebPage} criterion.
     * 
     * @param query The SQL-like AWQL query string.
     * @return A list of domain categories.
     * @throws ApiException if problems occur while parsing the query
     * or fetching domain categories.
     */
    public function queryDomainCategory($query)
    {
        $args = new QueryDomainCategory($query);
        $result = $this->__soapCall('queryDomainCategory', array($args));
        return $result->rval;
    }
}
