<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2015, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201506;

/**
   * A frequency cap is the maximum number of times an ad (or some set of ads) can
   * be shown to a user over a particular time period.
   * @package Google_Api_Ads_AdWords_v201506
   * @subpackage v201506
   */
class FrequencyCap
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/cm/v201506';
    const XSI_TYPE = 'FrequencyCap';
    /**
     * @access public
     * @var integer
     */
    public $impressions;
    /**
     * @access public
     * @var tnsTimeUnit
     */
    public $timeUnit;
    /**
     * @access public
     * @var tnsLevel
     */
    public $level;
    /**
     * Gets the namesapce of this class
     * @return the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($impressions = null, $timeUnit = null, $level = null)
    {
        $this->impressions = $impressions;
        $this->timeUnit = $timeUnit;
        $this->level = $level;
    }
}
