<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2015, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201506;
use Google\Api\Ads\AdWords\Lib\AdWordsSoapClient;

/**
   * TrafficEstimatorService
   * @package Google_Api_Ads_AdWords_v201506
   * @subpackage v201506
   */
class TrafficEstimatorService extends AdWordsSoapClient
{
    const SERVICE_NAME = 'TrafficEstimatorService';
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/o/v201506';
    const ENDPOINT = 'https://adwords.google.com/api/adwords/o/v201506/TrafficEstimatorService';
    /**
     * The endpoint of the service
     * @var string
     */
    public static $endpoint = 'https://adwords.google.com/api/adwords/o/v201506/TrafficEstimatorService';
    /**
     * Default class map for wsdl=>php
     * @access private
     * @var array
     */
    public static $classmap = array(
        'AdxError'                           => AdxError::class,
        'ApiError'                           => ApiError::class,
        'ApiException'                       => ApiException::class,
        'ApplicationException'               => ApplicationException::class,
        'AuthenticationError'                => AuthenticationError::class,
        'AuthorizationError'                 => AuthorizationError::class,
        'ClientTermsError'                   => ClientTermsError::class,
        'CollectionSizeError'                => CollectionSizeError::class,
        'ComparableValue'                    => ComparableValue::class,
        'Criterion'                          => Criterion::class,
        'DatabaseError'                      => DatabaseError::class,
        'DateError'                          => DateError::class,
        'DistinctError'                      => DistinctError::class,
        'DoubleValue'                        => DoubleValue::class,
        'EntityAccessDenied'                 => EntityAccessDenied::class,
        'EntityNotFound'                     => EntityNotFound::class,
        'IdError'                            => IdError::class,
        'InternalApiError'                   => InternalApiError::class,
        'Keyword'                            => Keyword::class,
        'Language'                           => Language::class,
        'Location'                           => Location::class,
        'LongValue'                          => LongValue::class,
        'MobileAppCategory'                  => MobileAppCategory::class,
        'MobileApplication'                  => MobileApplication::class,
        'Money'                              => Money::class,
        'NetworkSetting'                     => NetworkSetting::class,
        'NotEmptyError'                      => NotEmptyError::class,
        'NullError'                          => NullError::class,
        'NumberValue'                        => NumberValue::class,
        'OperationAccessDenied'              => OperationAccessDenied::class,
        'OperatorError'                      => OperatorError::class,
        'Placement'                          => Placement::class,
        'Platform'                           => Platform::class,
        'QuotaCheckError'                    => QuotaCheckError::class,
        'RangeError'                         => RangeError::class,
        'RateExceededError'                  => RateExceededError::class,
        'ReadOnlyError'                      => ReadOnlyError::class,
        'RegionCodeError'                    => RegionCodeError::class,
        'RejectedError'                      => RejectedError::class,
        'RequestError'                       => RequestError::class,
        'RequiredError'                      => RequiredError::class,
        'SizeLimitError'                     => SizeLimitError::class,
        'SoapHeader'                         => SoapRequestHeader::class,
        'SoapResponseHeader'                 => SoapResponseHeader::class,
        'StringFormatError'                  => StringFormatError::class,
        'StringLengthError'                  => StringLengthError::class,
        'CriterionUserInterest'              => CriterionUserInterest::class,
        'CriterionUserList'                  => CriterionUserList::class,
        'Vertical'                           => Vertical::class,
        'AdxError.Reason'                    => AdxErrorReason::class,
        'AuthenticationError.Reason'         => AuthenticationErrorReason::class,
        'AuthorizationError.Reason'          => AuthorizationErrorReason::class,
        'ClientTermsError.Reason'            => ClientTermsErrorReason::class,
        'CollectionSizeError.Reason'         => CollectionSizeErrorReason::class,
        'Criterion.Type'                     => CriterionType::class,
        'DatabaseError.Reason'               => DatabaseErrorReason::class,
        'DateError.Reason'                   => DateErrorReason::class,
        'DistinctError.Reason'               => DistinctErrorReason::class,
        'EntityAccessDenied.Reason'          => EntityAccessDeniedReason::class,
        'EntityNotFound.Reason'              => EntityNotFoundReason::class,
        'IdError.Reason'                     => IdErrorReason::class,
        'InternalApiError.Reason'            => InternalApiErrorReason::class,
        'KeywordMatchType'                   => KeywordMatchType::class,
        'LocationTargetingStatus'            => LocationTargetingStatus::class,
        'NotEmptyError.Reason'               => NotEmptyErrorReason::class,
        'NullError.Reason'                   => NullErrorReason::class,
        'OperationAccessDenied.Reason'       => OperationAccessDeniedReason::class,
        'OperatorError.Reason'               => OperatorErrorReason::class,
        'QuotaCheckError.Reason'             => QuotaCheckErrorReason::class,
        'RangeError.Reason'                  => RangeErrorReason::class,
        'RateExceededError.Reason'           => RateExceededErrorReason::class,
        'ReadOnlyError.Reason'               => ReadOnlyErrorReason::class,
        'RegionCodeError.Reason'             => RegionCodeErrorReason::class,
        'RejectedError.Reason'               => RejectedErrorReason::class,
        'RequestError.Reason'                => RequestErrorReason::class,
        'RequiredError.Reason'               => RequiredErrorReason::class,
        'SizeLimitError.Reason'              => SizeLimitErrorReason::class,
        'StringFormatError.Reason'           => StringFormatErrorReason::class,
        'StringLengthError.Reason'           => StringLengthErrorReason::class,
        'CriterionUserList.MembershipStatus' => CriterionUserListMembershipStatus::class,
        'AdGroupEstimate'                    => AdGroupEstimate::class,
        'AdGroupEstimateRequest'             => AdGroupEstimateRequest::class,
        'CampaignEstimate'                   => CampaignEstimate::class,
        'CampaignEstimateRequest'            => CampaignEstimateRequest::class,
        'CurrencyCodeError'                  => CurrencyCodeError::class,
        'Estimate'                           => Estimate::class,
        'EstimateRequest'                    => EstimateRequest::class,
        'KeywordEstimate'                    => KeywordEstimate::class,
        'KeywordEstimateRequest'             => KeywordEstimateRequest::class,
        'StatsEstimate'                      => StatsEstimate::class,
        'TrafficEstimatorError'              => TrafficEstimatorError::class,
        'TrafficEstimatorResult'             => TrafficEstimatorResult::class,
        'TrafficEstimatorSelector'           => TrafficEstimatorSelector::class,
        'CurrencyCodeError.Reason'           => CurrencyCodeErrorReason::class,
        'TrafficEstimatorError.Reason'       => TrafficEstimatorErrorReason::class,
        'get'                                => TrafficEstimatorServiceGet::class,
        'getResponse'                        => TrafficEstimatorServiceGetResponse::class,
    );

    /**
     * Constructor using wsdl location and options array
     * @param string $wsdl WSDL location for this service
     * @param array $options Options for the SoapClient
     */
    public function __construct($wsdl, $options, $user)
    {
        $options['classmap'] = self::$classmap;
        parent::__construct($wsdl, $options, $user, self::SERVICE_NAME, self::WSDL_NAMESPACE);
    }
    /**
     * <span class="constraint Required">This field is required and should not be {@code null}.</span>
     * 
     * 
     * 
     * Returns traffic estimates for specified criteria.
     * 
     * @param selector Campaigns, ad groups and keywords for which traffic
     * should be estimated.
     * @return Traffic estimation results.
     * @throws ApiException if problems occurred while retrieving estimates
     */
    public function get($selector)
    {
        $args = new TrafficEstimatorServiceGet($selector);
        $result = $this->__soapCall('get', array($args));
        return $result->rval;
    }
}
