<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2015, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\Common\Util;

/**
 * A collection of utility methods for reading API property files.
 * @package GoogleApiAdsCommon
 * @subpackage Util
 */
class ApiPropertiesUtils
{
    /**
     * Parses the specified API properties file.
     * @param string $propsFilePath the path to the API properties file to parse
     * @return array the parsed properties
     */
    public static function ParseApiPropertiesFile($propsFilePath)
    {
        return parse_ini_file($propsFilePath);
    }
}
