<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201603;



/**
   * Structure to specify an address location.
   * 
   * 
   * 
   * Structure to specify an address location.
   * @package Google_Api_Ads_AdWords_v201603
   * @subpackage v201603
   */
class Address
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/cm/v201603';
    const XSI_TYPE = 'Address';
    /**
     * @access public
     * @var string
     */
    public $streetAddress;
    /**
     * @access public
     * @var string
     */
    public $streetAddress2;
    /**
     * @access public
     * @var string
     */
    public $cityName;
    /**
     * @access public
     * @var string
     */
    public $provinceCode;
    /**
     * @access public
     * @var string
     */
    public $provinceName;
    /**
     * @access public
     * @var string
     */
    public $postalCode;
    /**
     * @access public
     * @var string
     */
    public $countryCode;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($streetAddress = null, $streetAddress2 = null, $cityName = null, $provinceCode = null, $provinceName = null, $postalCode = null, $countryCode = null)
    {
        $this->streetAddress = $streetAddress;
        $this->streetAddress2 = $streetAddress2;
        $this->cityName = $cityName;
        $this->provinceCode = $provinceCode;
        $this->provinceName = $provinceName;
        $this->postalCode = $postalCode;
        $this->countryCode = $countryCode;
    }
}
