<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201603;



/**
   * Holds fields that provide information on the last set of values that were passed in through
   * the parent BudgetOrder for mutate.add and mutate.set.
   * <span class="constraint Billing">This element only applies if manager account is whitelisted for new billing backend.</span>
   * @package Google_Api_Ads_AdWords_v201603
   * @subpackage v201603
   */
class BudgetOrderRequest
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/billing/v201603';
    const XSI_TYPE = 'BudgetOrderRequest';
    /**
     * @access public
     * @var BudgetOrderRequestStatus
     */
    public $status;
    /**
     * @access public
     * @var string
     */
    public $date;
    /**
     * @access public
     * @var string
     */
    public $billingAccountName;
    /**
     * @access public
     * @var string
     */
    public $poNumber;
    /**
     * @access public
     * @var string
     */
    public $budgetOrderName;
    /**
     * @access public
     * @var Money
     */
    public $spendingLimit;
    /**
     * @access public
     * @var string
     */
    public $startDateTime;
    /**
     * @access public
     * @var string
     */
    public $endDateTime;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($status = null, $date = null, $billingAccountName = null, $poNumber = null, $budgetOrderName = null, $spendingLimit = null, $startDateTime = null, $endDateTime = null)
    {
        $this->status = $status;
        $this->date = $date;
        $this->billingAccountName = $billingAccountName;
        $this->poNumber = $poNumber;
        $this->budgetOrderName = $budgetOrderName;
        $this->spendingLimit = $spendingLimit;
        $this->startDateTime = $startDateTime;
        $this->endDateTime = $endDateTime;
    }
}
