<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201603;



/**
   * Represents a customer for the CustomerService.
   * @package Google_Api_Ads_AdWords_v201603
   * @subpackage v201603
   */
class Customer
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/mcm/v201603';
    const XSI_TYPE = 'Customer';
    /**
     * @access public
     * @var integer
     */
    public $customerId;
    /**
     * @access public
     * @var string
     */
    public $currencyCode;
    /**
     * @access public
     * @var string
     */
    public $dateTimeZone;
    /**
     * @access public
     * @var string
     */
    public $descriptiveName;
    /**
     * @access public
     * @var string
     */
    public $companyName;
    /**
     * @access public
     * @var boolean
     */
    public $canManageClients;
    /**
     * @access public
     * @var boolean
     */
    public $testAccount;
    /**
     * @access public
     * @var boolean
     */
    public $autoTaggingEnabled;
    /**
     * @access public
     * @var string
     */
    public $trackingUrlTemplate;
    /**
     * @access public
     * @var ConversionTrackingSettings
     */
    public $conversionTrackingSettings;
    /**
     * @access public
     * @var RemarketingSettings
     */
    public $remarketingSettings;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($customerId = null, $currencyCode = null, $dateTimeZone = null, $descriptiveName = null, $companyName = null, $canManageClients = null, $testAccount = null, $autoTaggingEnabled = null, $trackingUrlTemplate = null, $conversionTrackingSettings = null, $remarketingSettings = null)
    {
        $this->customerId = $customerId;
        $this->currencyCode = $currencyCode;
        $this->dateTimeZone = $dateTimeZone;
        $this->descriptiveName = $descriptiveName;
        $this->companyName = $companyName;
        $this->canManageClients = $canManageClients;
        $this->testAccount = $testAccount;
        $this->autoTaggingEnabled = $autoTaggingEnabled;
        $this->trackingUrlTemplate = $trackingUrlTemplate;
        $this->conversionTrackingSettings = $conversionTrackingSettings;
        $this->remarketingSettings = $remarketingSettings;
    }
}
