<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201603;



/**
   * <span class="constraint ContentsNotNull">This field must not contain {@code null} elements.</span>
   * <span class="constraint NotEmpty">This field must contain at least one element.</span>
   * <span class="constraint Required">This field is required and should not be {@code null}.</span>
   * <span class="constraint SupportedOperators">The following {@link Operator}s are supported: ADD.</span>
   * 
   * 
   * 
   * Reports an offline conversion for each entry in {@code operations}.
   * <p>
   * This bulk operation does not have any transactional guarantees. Some operations can succeed
   * while others fail.
   * 
   * @param operations A list of offline conversion feed operations.
   * @return The list of offline conversion feed results (in the same order as the operations).
   * @throws {@link ApiException} if problems occurred while applying offline conversions.
   * @package Google_Api_Ads_AdWords_v201603
   * @subpackage v201603
   */
class OfflineConversionFeedServiceMutate
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/cm/v201603';
    const XSI_TYPE = '';
    /**
     * @access public
     * @var OfflineConversionFeedOperation[]
     */
    public $operations;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($operations = null)
    {
        $this->operations = $operations;
    }
}
