<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201603;



/**
   * SimilarUserList is a list of users which are similar to users from another UserList.
   * These lists are readonly and automatically created by google.
   * @package Google_Api_Ads_AdWords_v201603
   * @subpackage v201603
   */
class SimilarUserList extends UserList
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/rm/v201603';
    const XSI_TYPE = 'SimilarUserList';
    /**
     * @access public
     * @var integer
     */
    public $seedUserListId;
    /**
     * @access public
     * @var string
     */
    public $seedUserListName;
    /**
     * @access public
     * @var string
     */
    public $seedUserListDescription;
    /**
     * @access public
     * @var UserListMembershipStatus
     */
    public $seedUserListStatus;
    /**
     * @access public
     * @var integer
     */
    public $seedListSize;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($seedUserListId = null, $seedUserListName = null, $seedUserListDescription = null, $seedUserListStatus = null, $seedListSize = null, $id = null, $isReadOnly = null, $name = null, $description = null, $status = null, $integrationCode = null, $accessReason = null, $accountUserListStatus = null, $membershipLifeSpan = null, $size = null, $sizeRange = null, $sizeForSearch = null, $sizeRangeForSearch = null, $listType = null, $isEligibleForSearch = null, $isEligibleForDisplay = null, $UserListType = null)
    {
        parent::__construct();
        $this->seedUserListId = $seedUserListId;
        $this->seedUserListName = $seedUserListName;
        $this->seedUserListDescription = $seedUserListDescription;
        $this->seedUserListStatus = $seedUserListStatus;
        $this->seedListSize = $seedListSize;
        $this->id = $id;
        $this->isReadOnly = $isReadOnly;
        $this->name = $name;
        $this->description = $description;
        $this->status = $status;
        $this->integrationCode = $integrationCode;
        $this->accessReason = $accessReason;
        $this->accountUserListStatus = $accountUserListStatus;
        $this->membershipLifeSpan = $membershipLifeSpan;
        $this->size = $size;
        $this->sizeRange = $sizeRange;
        $this->sizeForSearch = $sizeForSearch;
        $this->sizeRangeForSearch = $sizeRangeForSearch;
        $this->listType = $listType;
        $this->isEligibleForSearch = $isEligibleForSearch;
        $this->isEligibleForDisplay = $isEligibleForDisplay;
        $this->UserListType = $UserListType;
    }
}
