<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2015, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\Common\Lib;
use Exception;

/**
 * Exception class for any client library error related to obtaining a service.
 * @package GoogleApiAdsCommon
 * @subpackage Lib
 */
class ServiceException extends Exception
{
    /**
     * Creates a new instance of this service exception.
     * @param string $message the exception message
     * @param int $code user defined exception code
     * @param Exception $previous previous exception if nested exception
     */
    public function __construct($message, $code = 0, Exception $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }
}
